# Generated by Django 4.2.1 on 2023-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unviewed',
            field=models.IntegerField(),
        ),
    ]
