# Generated by Django 4.2.1 on 2023-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_unviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unviewed',
        ),
        migrations.AddField(
            model_name='send',
            name='unviewed',
            field=models.IntegerField(default=0),
        ),
    ]
