# Generated by Django 4.2.1 on 2023-05-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='settings.profile')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='settings.profile')),
            ],
        ),
    ]
